local:
  api-key: gXXR5ag6tDhrKgf1AnegQFbbWys/hfxqiop7ySyzNpkvtiGItYiutjleCZe84pjejrlFAqaaLCkll3pD1AfZVw==
  postgres:
    host: localhost
    port: 5432
    name: ams_local
    user: startconnect_local
    password:

dev:
  api-key: gXXR5ag6tDhrKgf1AnegQFbbWys/hfxqiop7ySyzNpkvtiGItYiutjleCZe84pjejrlFAqaaLCkll3pD1AfZVw==
  postgres:
    host: ec2-174-129-227-205.compute-1.amazonaws.com
    port: 5432
    name: d9fomasoovosfq
    user: lujzsilupgqxun
    password: 45f2533919be82597aab3ad65c68656918ce755f395389e4b4fecd93a1c542c3

test:
  postgres:
    host: localhost
    port: 5432
    name: unit_test
    user: unit_test
    password: