local:
  postgres:
    host: localhost
    port: 5432
    name: ams_local
    user: startconnect_local
    password:

dev:
  postgres:
    host: ec2-107-22-160-185.compute-1.amazonaws.com
    port: 5432
    name: dfmit72pe4i3r6
    user: sazfghatoecpmm
    password: e990294ff3af6cd53a2d5ff76d6ce674387c926f0fcb1023910e7c434759654f

test:
  postgres:
    host: localhost
    port: 5432
    name: unit_test
    user: unit_test
    password: